
export const INSTRUMENT_TYPE_CHORD = "ChordInstrument"
export const INSTRUMENT_TYPE_SOUNDFONT = "SoundFontInstrument"
export const INSTRUMENT_TYPE_OSCILLATOR = "OscillatorInstrument"
export const INSTRUMENT_TYPE_DUAL_OSCILLATOR = "DualOscillatorInstrument"
export const INSTRUMENT_TYPE_TRIPLE_OSCILLATOR = "TripleOscillatorInstrument"
export const INSTRUMENT_TYPE_WAM = "WAMInstrument"
export const INSTRUMENT_TYPE_WAM2 = "WAM2Instrument"
export const INSTRUMENT_TYPE_WAVEGUIDE = "WaveGuideInstrument"
export const INSTRUMENT_TYPE_SYTHESIZER = "SynthesizerInstrument"
export const INSTRUMENT_TYPE_MONOTRON = "MonotronInstrument"
export const INSTRUMENT_TYPE_MOOG = "MoogInstrument"
export const INSTRUMENT_TYPE_MIDI = "MIDIInstrument"
export const INSTRUMENT_TYPE_SPEECH = "SpeechInstrument"
export const INSTRUMENT_TYPE_KIT = "KitInstrument"
export const INSTRUMENT_TYPE_DRUMKIT = "DrumkitInstrument"

export const INSTRUMENTS = [
	INSTRUMENT_TYPE_OSCILLATOR,
	INSTRUMENT_TYPE_DUAL_OSCILLATOR,
	INSTRUMENT_TYPE_TRIPLE_OSCILLATOR,
	
	INSTRUMENT_TYPE_CHORD,
	INSTRUMENT_TYPE_SOUNDFONT,
	
	INSTRUMENT_TYPE_WAM,
	INSTRUMENT_TYPE_WAM2,
	INSTRUMENT_TYPE_WAVEGUIDE,
	INSTRUMENT_TYPE_SYTHESIZER,
	INSTRUMENT_TYPE_MONOTRON,
	INSTRUMENT_TYPE_MOOG,
	INSTRUMENT_TYPE_SPEECH,
	INSTRUMENT_TYPE_DRUMKIT,
	INSTRUMENT_TYPE_MIDI,
	INSTRUMENT_TYPE_KIT
]