blockExoticSubdeps: false

allowBuilds:
  '@parcel/watcher': false
  '@serialport/bindings-cpp': false
  '@swc/core': false
  bufferutil: false
  core-js: false
  electron-winstaller: false
  esbuild: false
  lmdb: false
  midi-writer-js: false
  msgpackr-extract: false
  netronome@https://codeload.github.com/designerzen/netronome/tar.gz/26cd23d66cec473616130f6b72ba4754058fb82e: true
  phantomjs-prebuilt: false
  sharp: false
  unrs-resolver: false
  utf-8-validate: false
  workerd: false

minimumReleaseAgeExclude:
  - '@audio/decode@3.11.1'
  - abcjs@6.6.4
  - audio-decode@3.11.2
  - postcss@8.5.17 || 8.5.19 || 8.5.22 || 8.5.23
  - svgo@4.0.2
  - '@babylonjs/core@9.17.1 || 9.18.0'
  - '@babylonjs/gui-editor@9.17.1 || 9.18.0'
  - '@babylonjs/inspector@9.17.1 || 9.18.0'
  - '@babylonjs/loaders@9.17.1 || 9.18.0'
  - '@babylonjs/materials@9.17.1 || 9.18.0'
  - electron@43.2.0
  - knip@6.28.0 || 6.29.0 || 6.32.1
  - '@electron/packager@20.0.4'
  - sass@1.101.6 || 1.101.7 || 1.102.0
  - troika-3d@0.53.0
  - troika-animation@0.53.0
  - troika-core@0.53.0
  - troika-three-text@0.53.0
  - troika-three-utils@0.53.0
  - troika-worker-utils@0.53.0
  - concurrently@10.0.4
