export const DISPLAY_MEDIA_PIPE_2D = "DisplayMediaPipe2D"
export const DISPLAY_WEB_GL_3D = "DisplayWebGL3D"
export const DISPLAY_WEB_GPU_3D = "DisplayWebGPU3D"
export const DISPLAY_THREE_WEBGPU_PARTICLE = "DisplayThreeWebGPUParticle"
export const DISPLAY_BABYLON_3D = "DisplayBabylon3D"
export const DISPLAY_MEDIA_VISION_2D = "DisplayMediaVision2D"
export const DISPLAY_LOOKING_GLASS_3D = "DisplayLookingGlass3D"
export const DISPLAY_LOOKING_GLASS_WEBGPU = "DisplayLookingGlassWebGPU"
export const DISPLAY_LOOKING_GLASS_3D_WEBGPU_TSL = "DisplayLookingGlass3DWebGPUTSL"
export const DISPLAY_CANVAS_2D = "DisplayCanvas2D"
export const DISPLAY_COMPOSITE = "DisplayComposite"

export const DISPLAY_TYPES = {
	DISPLAY_MEDIA_VISION_2D, 
	DISPLAY_MEDIA_PIPE_2D,
	DISPLAY_LOOKING_GLASS_3D, 
	DISPLAY_LOOKING_GLASS_WEBGPU,
	DISPLAY_LOOKING_GLASS_3D_WEBGPU_TSL,
	DISPLAY_WEB_GL_3D, 
	DISPLAY_WEB_GPU_3D,
	DISPLAY_BABYLON_3D,
	DISPLAY_THREE_WEBGPU_PARTICLE,
	DISPLAY_CANVAS_2D,
	DISPLAY_COMPOSITE
}