name: Deploy to “interface.place” via GitHub Pages

on:
     # Trigger the workflow every time you push to the `main` branch
    push:
        branches: [ main ]

      # Allows you to run this workflow manually from the Actions tab on GitHub.
    workflow_dispatch:

    # Allow this job to clone the repo and create a page deployment
permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checks out this repository using git
              uses: actions/checkout@v4

            # Install pnpm
            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                run_install: false
                version: 9.15.3

            # Install node js
            - name: Install Node.js 22+
              uses: actions/setup-node@v4
              with:
                node-version-file: ".nvmrc"
                cache: pnpm

            # Install project node dependencies
            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            # Build command
            - name: Build the app into dist
              run: pnpm run build --if-present

            # - name: List the current folder contents...
            #   run: ls ./

            - name: List the build folder contents...
              run: ls ./release/web

            - name: Upload artifact
			  id: deployment
            #   uses: actions/upload-artifact@v4
			  uses: actions/upload-pages-artifact@v3
              with:
                name: github-pages
                path: ./release/web

    deploy:
	
        # Add a dependency to the build job
        needs: build
		    
		 # Specify runner + deployment step
        runs-on: ubuntu-latest

        # Deploy to the github-pages environment
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
        permissions:
            pages: write      # to deploy to Pages
            id-token: write   # to verify the deployment originates from an appropriate source
    
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
